import { CfnWorkspace, CfnWorkspaceProps } from 'aws-cdk-lib/aws-grafana';
import { IRole } from 'aws-cdk-lib/aws-iam';
import { Construct } from 'constructs';
import {
  AccountAccessType,
  AuthenticationProviders,
  IWorkspace,
  NetworkAccessControl,
  NotificationDestinations,
  PermissionTypes,
  SamlConfiguration,
  VpcConfiguration,
  WorkspaceBase,
} from './workspace-base';

/**
 * Properties for creating an Amazon Managed Grafana workspace.
 */
export interface WorkspaceProps {
  /**
   * Specifies whether the workspace can access AWS resources in this AWS account only, or whether
   * it can also access AWS resources in other accounts in the same organization. If this is
   * ORGANIZATION, the OrganizationalUnits parameter specifies which organizational units the
   * workspace can access.
   *
   * Required field.
   */
  readonly accountAccessType: AccountAccessType;

  /**
   * Specifies whether this workspace uses SAML 2.0, AWS IAM Identity Center, or both to
   * authenticate users for using the Grafana console within a workspace.
   *
   * Required field.
   */
  readonly authenticationProviders: AuthenticationProviders[];

  /**
   * A unique, case-sensitive, user-provided identifier to ensure the idempotency of the request.
   *
   * Must be 1-64 characters long and contain only printable ASCII characters (validated by
   * CloudFormation at deploy time). Note that an idempotency token has no practical effect in the
   * declarative CloudFormation/CDK deployment model.
   *
   * @default - no client token
   */
  readonly clientToken?: string;

  /**
   * Specifies the AWS data sources that have been configured to have IAM roles and permissions
   * created to allow Amazon Managed Grafana to read data from these sources.
   * This list is only used when the workspace was created through the AWS console, and the
   * permissionType is SERVICE_MANAGED. The Amazon Managed Grafana API marks this parameter as for
   * internal use only and recommends against setting it.
   *
   * @default - no data sources
   */
  readonly dataSources?: string[];

  /**
   * The user-defined description of the workspace.
   *
   * Maximum length of 2048 characters (validated by CloudFormation at deploy time).
   *
   * @default - no description
   */
  readonly description?: string;

  /**
   * Specifies the version of Grafana to support in the workspace. Defaults to the latest version
   * on create (for example, 10.4), or the current version of the workspace on update.
   * Can only be used to upgrade (for example, from 8.4 to 9.4), not downgrade (for example, from
   * 9.4 to 8.4).
   *
   * Must be 1-255 characters long (validated by CloudFormation at deploy time).
   *
   * @default - the service assigns the latest Grafana version
   */
  readonly grafanaVersion?: string;

  /**
   * The name of the workspace.
   *
   * Must be 1-255 characters long and contain only alphanumeric characters, hyphens, dots,
   * underscores, and tildes (validated by CloudFormation at deploy time).
   *
   * @default - a name is generated by CloudFormation
   */
  readonly name?: string;

  /**
   * The configuration settings for network access to your workspace.
   *
   * @default - no network access control, the workspace is open to all traffic
   */
  readonly networkAccessControl?: NetworkAccessControl;

  /**
   * The AWS notification channels that Amazon Managed Grafana can automatically create IAM roles
   * and permissions for, to allow Amazon Managed Grafana to use these channels.
   *
   * @default - no notification destinations
   */
  readonly notificationDestinations?: NotificationDestinations[];

  /**
   * Specifies the organizational units that this workspace is allowed to use data sources from, if
   * this workspace is in an account that is part of an organization.
   *
   * @default - no organizational units
   */
  readonly organizationalUnits?: string[];

  /**
   * Name of the IAM role to use for the organization.
   *
   * Maximum length of 2048 characters (validated by CloudFormation at deploy time).
   *
   * @default - no organization role name
   */
  readonly organizationRoleName?: string;

  /**
   * If this is SERVICE_MANAGED, and the workplace was created through the Amazon Managed Grafana
   * console, then Amazon Managed Grafana automatically creates the IAM roles and provisions the
   * permissions that the workspace needs to use AWS data sources and notification channels.
   *
   * If this is CUSTOMER_MANAGED, you must manage those roles and permissions yourself.
   *
   * If you are working with a workspace in a member account of an organization and that account is
   * not a delegated administrator account, and you want the workspace to access data sources in
   * other AWS accounts in the organization, this parameter must be set to CUSTOMER_MANAGED.
   *
   * Required field.
   */
  readonly permissionType: PermissionTypes;

  /**
   * Whether plugin administration is enabled in the workspace. Setting to true allows workspace
   * admins to install, uninstall, and update plugins from within the Grafana workspace.
   *
   * This option is only valid for workspaces that support Grafana version 9 or newer.
   *
   * @default - false
   */
  readonly pluginAdminEnabled?: boolean;

  /**
   * The IAM role that grants permissions to the AWS resources that the workspace will view data
   * from.
   *
   * @default - no role is attached
   */
  readonly role?: IRole;

  /**
   * If the workspace uses SAML, use this structure to map SAML assertion attributes to workspace
   * user information and define which groups in the assertion attribute are to have the Admin and
   * Editor roles in the workspace.
   *
   * @default - no SAML configuration
   */
  readonly samlConfiguration?: SamlConfiguration;

  /**
   * The name of the AWS CloudFormation stack set that is used to generate IAM roles to be used for
   * this workspace.
   *
   * @default - no stack set name
   */
  readonly stackSetName?: string;

  /**
   * A map of tags to assign to the workspace. Tags can also be applied after creation using
   * `Tags.of(workspace).add(key, value)`.
   *
   * Constraints (from the Amazon Managed Grafana API): a maximum of 50 tags, each key must be
   * 1-128 characters long and each value 0-256 characters long (validated by CloudFormation at
   * deploy time).
   *
   * @default - no tags
   */
  readonly tags?: { [key: string]: string };

  /**
   * The configuration settings for an Amazon VPC that contains data sources for your Grafana
   * workspace to connect to.
   *
   * @default - no VPC connection
   */
  readonly vpcConfiguration?: VpcConfiguration;
}

export interface WorkspaceAttributes {
  /**
   * Specifies whether the workspace can access AWS resources in this AWS account only, or whether
   * it can also access AWS resources in other accounts in the same organization. If this is
   * ORGANIZATION, the OrganizationalUnits parameter specifies which organizational units the
   * workspace can access.
   *
   * Required field.
   */
  readonly accountAccessType: AccountAccessType;

  /**
   * Specifies whether this workspace uses SAML 2.0, AWS IAM Identity Center, or both to
   * authenticate users for using the Grafana console within a workspace.
   *
   * Required field.
   */
  readonly authenticationProviders: AuthenticationProviders[];

  /**
   * A unique, case-sensitive, user-provided identifier to ensure the idempotency of the request.
   *
   * Must be 1-64 characters long and contain only printable ASCII characters (validated by
   * CloudFormation at deploy time). Note that an idempotency token has no practical effect in the
   * declarative CloudFormation/CDK deployment model.
   *
   * @default - no client token
   */
  readonly clientToken?: string;

  /**
   * Specifies the AWS data sources that have been configured to have IAM roles and permissions
   * created to allow Amazon Managed Grafana to read data from these sources.
   * This list is only used when the workspace was created through the AWS console, and the
   * permissionType is SERVICE_MANAGED. The Amazon Managed Grafana API marks this parameter as for
   * internal use only and recommends against setting it.
   *
   * @default - no data sources
   */
  readonly dataSources?: string[];

  /**
   * The user-defined description of the workspace.
   *
   * Maximum length of 2048 characters (validated by CloudFormation at deploy time).
   *
   * @default - no description
   */
  readonly description?: string;

  /**
   * The name of the workspace.
   *
   * Must be 1-255 characters long and contain only alphanumeric characters, hyphens, dots,
   * underscores, and tildes (validated by CloudFormation at deploy time).
   *
   * @default - a name is generated by CloudFormation
   */
  readonly name?: string;

  /**
   * The configuration settings for network access to your workspace.
   *
   * @default - no network access control, the workspace is open to all traffic
   */
  readonly networkAccessControl?: NetworkAccessControl;

  /**
   * The AWS notification channels that Amazon Managed Grafana can automatically create IAM roles
   * and permissions for, to allow Amazon Managed Grafana to use these channels.
   *
   * @default - no notification destinations
   */
  readonly notificationDestinations?: NotificationDestinations[];

  /**
   * Specifies the organizational units that this workspace is allowed to use data sources from, if
   * this workspace is in an account that is part of an organization.
   *
   * @default - no organizational units
   */
  readonly organizationalUnits?: string[];

  /**
   * Name of the IAM role to use for the organization.
   *
   * Maximum length of 2048 characters (validated by CloudFormation at deploy time).
   *
   * @default - no organization role name
   */
  readonly organizationRoleName?: string;

  /**
   * If this is SERVICE_MANAGED, and the workplace was created through the Amazon Managed Grafana
   * console, then Amazon Managed Grafana automatically creates the IAM roles and provisions the
   * permissions that the workspace needs to use AWS data sources and notification channels.
   *
   * If this is CUSTOMER_MANAGED, you must manage those roles and permissions yourself.
   *
   * If you are working with a workspace in a member account of an organization and that account is
   * not a delegated administrator account, and you want the workspace to access data sources in
   * other AWS accounts in the organization, this parameter must be set to CUSTOMER_MANAGED.
   *
   * Required field.
   */
  readonly permissionType: PermissionTypes;

  /**
   * Whether plugin administration is enabled in the workspace. Setting to true allows workspace
   * admins to install, uninstall, and update plugins from within the Grafana workspace.
   *
   * This option is only valid for workspaces that support Grafana version 9 or newer.
   *
   * @default - false
   */
  readonly pluginAdminEnabled?: boolean;

  /**
   * The IAM role that grants permissions to the AWS resources that the workspace will view data
   * from.
   *
   * @default - no role is attached
   */
  readonly role?: IRole;

  /**
   * If the workspace uses SAML, use this structure to map SAML assertion attributes to workspace
   * user information and define which groups in the assertion attribute are to have the Admin and
   * Editor roles in the workspace.
   *
   * @default - no SAML configuration
   */
  readonly samlConfiguration?: SamlConfiguration;

  /**
   * The name of the AWS CloudFormation stack set that is used to generate IAM roles to be used for
   * this workspace.
   *
   * @default - no stack set name
   */
  readonly stackSetName?: string;

  /**
   * The configuration settings for an Amazon VPC that contains data sources for your Grafana
   * workspace to connect to.
   *
   * @default - no VPC connection
   */
  readonly vpcConfiguration?: VpcConfiguration;

  /**
   * The arn of this workspace.
   */
  readonly workspaceArn: string;
};

const IS_WORKSPACE = Symbol.for('@robhan-cdk-lib/aws_grafana.Workspace');

/**
 * Specifies a workspace. In a workspace, you can create Grafana dashboards and visualizations to
 * analyze your metrics, logs, and traces. You don't have to build, package, or deploy any hardware
 * to run the Grafana server.
 */
export class Workspace extends WorkspaceBase {
  public static isWorkspace(x: any): x is Workspace {
    return IS_WORKSPACE in x;
  }

  /**
   * Import an existing workspace from its ARN.
   *
   * A single ARN is the most common handle for referencing an existing workspace. The imported
   * workspace only exposes identity information (`workspaceArn` and `workspaceId`); the create-time
   * configuration properties are not available on an ARN import. Use `fromWorkspaceAttributes` when
   * those properties are required.
   *
   * @param scope The parent construct
   * @param id The construct id
   * @param workspaceArn The ARN of the existing workspace
   */
  public static fromWorkspaceArn(scope: Construct, id: string, workspaceArn: string): IWorkspace {
    class Import extends WorkspaceBase {
      public readonly accountAccessType?: AccountAccessType;
      public readonly authenticationProviders?: AuthenticationProviders[];
      public readonly clientToken?: string;
      public readonly dataSources?: string[];
      public readonly description?: string;
      public readonly name?: string;
      public readonly networkAccessControl?: NetworkAccessControl;
      public readonly notificationDestinations?: NotificationDestinations[];
      public readonly organizationalUnits?: string[];
      public readonly organizationRoleName?: string;
      public readonly permissionType?: PermissionTypes;
      public readonly pluginAdminEnabled?: boolean;
      public readonly role?: IRole;
      public readonly samlConfiguration?: SamlConfiguration;
      public readonly stackSetName?: string;
      public readonly vpcConfiguration?: VpcConfiguration;
      public readonly creationTimestamp?: string;
      public readonly endpoint?: string;
      public readonly grafanaVersion?: string;
      public readonly modificationTimestamp?: string;
      public readonly samlConfigurationStatus?: string;
      public readonly ssoClientId?: string;
      public readonly status?: string;
      public readonly workspaceArn: string;
      public readonly workspaceId: string;

      public constructor() {
        super(scope, id);

        this.workspaceArn = workspaceArn;
        this.workspaceId = this.getWorkspaceId(workspaceArn);
      }
    }

    return new Import();
  }

  public static fromWorkspaceAttributes(scope: Construct, id: string, attrs: WorkspaceAttributes): IWorkspace {
    class Import extends WorkspaceBase {
      public readonly accountAccessType: AccountAccessType;
      public readonly authenticationProviders: AuthenticationProviders[];
      public readonly clientToken?: string;
      public readonly dataSources?: string[];
      public readonly description?: string;
      public readonly name?: string;
      public readonly networkAccessControl?: NetworkAccessControl;
      public readonly notificationDestinations?: NotificationDestinations[];
      public readonly organizationalUnits?: string[];
      public readonly organizationRoleName?: string;
      public readonly permissionType: PermissionTypes;
      public readonly pluginAdminEnabled?: boolean;
      public readonly role?: IRole;
      public readonly samlConfiguration?: SamlConfiguration;
      public readonly stackSetName?: string;
      public readonly vpcConfiguration?: VpcConfiguration;
      public readonly creationTimestamp?: string;
      public readonly endpoint?: string;
      public readonly grafanaVersion?: string;
      public readonly modificationTimestamp?: string;
      public readonly samlConfigurationStatus?: string;
      public readonly ssoClientId?: string;
      public readonly status?: string;
      public readonly workspaceArn: string;
      public readonly workspaceId: string;

      public constructor(attributes: WorkspaceAttributes) {
        super(scope, id);

        this.accountAccessType = attributes.accountAccessType;
        this.authenticationProviders = attributes.authenticationProviders;
        this.clientToken = attributes.clientToken;
        this.dataSources = attributes.dataSources;
        this.description = attributes.description;
        this.name = attributes.name;
        this.networkAccessControl = attributes.networkAccessControl;
        this.notificationDestinations = attributes.notificationDestinations;
        this.organizationalUnits = attributes.organizationalUnits;
        this.organizationRoleName = attributes.organizationRoleName;
        this.permissionType = attributes.permissionType;
        this.pluginAdminEnabled = attributes.pluginAdminEnabled;
        this.role = attributes.role;
        this.samlConfiguration = attributes.samlConfiguration;
        this.stackSetName = attributes.stackSetName;
        this.vpcConfiguration = attributes.vpcConfiguration;
        this.workspaceArn = attributes.workspaceArn;
        this.workspaceId = this.getWorkspaceId(attributes.workspaceArn);
      }
    }

    return new Import(attrs);
  }

  /**
   * Specifies whether the workspace can access AWS resources in this AWS account only, or whether
   * it can also access AWS resources in other accounts in the same organization. If this is
   * ORGANIZATION, the OrganizationalUnits parameter specifies which organizational units the
   * workspace can access.
   *
   * Always populated for a workspace created through this construct (it is a required prop).
   */
  public readonly accountAccessType?: AccountAccessType;

  /**
   * Specifies whether this workspace uses SAML 2.0, AWS IAM Identity Center, or both to
   * authenticate users for using the Grafana console within a workspace.
   *
   * Always populated for a workspace created through this construct (it is a required prop).
   */
  public readonly authenticationProviders?: AuthenticationProviders[];

  /**
   * A unique, case-sensitive, user-provided identifier to ensure the idempotency of the request.
   */
  public readonly clientToken?: string;

  /**
   * Specifies the AWS data sources that have been configured to have IAM roles and permissions
   * created to allow Amazon Managed Grafana to read data from these sources.
   *
   * This list is only used when the workspace was created through the AWS console, and the
   * permissionType is SERVICE_MANAGED.
   */
  public readonly dataSources?: string[];

  /**
   * The user-defined description of the workspace.
   */
  public readonly description?: string;

  /**
   * The name of the workspace.
   */
  public readonly name?: string;

  /**
   * The configuration settings for network access to your workspace.
   */
  public readonly networkAccessControl?: NetworkAccessControl;

  /**
   * The AWS notification channels that Amazon Managed Grafana can automatically create IAM roles
   * and permissions for, to allow Amazon Managed Grafana to use these channels.
   */
  public readonly notificationDestinations?: NotificationDestinations[];

  /**
   * Specifies the organizational units that this workspace is allowed to use data sources from, if
   * this workspace is in an account that is part of an organization.
   */
  public readonly organizationalUnits?: string[];

  /**
   * The name of the IAM role that is used to access resources through Organizations.
   */
  public readonly organizationRoleName?: string;

  /**
   * If this is SERVICE_MANAGED, and the workplace was created through the Amazon Managed Grafana
   * console, then Amazon Managed Grafana automatically creates the IAM roles and provisions the
   * permissions that the workspace needs to use AWS data sources and notification channels.
   *
   * If this is CUSTOMER_MANAGED, you must manage those roles and permissions yourself.
   *
   * If you are working with a workspace in a member account of an organization and that account is
   * not a delegated administrator account, and you want the workspace to access data sources in
   * other AWS accounts in the organization, this parameter must be set to CUSTOMER_MANAGED.
   *
   * Always populated for a workspace created through this construct (it is a required prop).
   */
  public readonly permissionType?: PermissionTypes;

  /**
   * Whether plugin administration is enabled in the workspace. Setting to true allows workspace
   * admins to install, uninstall, and update plugins from within the Grafana workspace.
   *
   * This option is only valid for workspaces that support Grafana version 9 or newer.
   */
  public readonly pluginAdminEnabled?: boolean;

  /**
   * The IAM role that grants permissions to the AWS resources that the workspace will view data
   * from.
   */
  public readonly role?: IRole;

  /**
   * If the workspace uses SAML, use this structure to map SAML assertion attributes to workspace
   * user information and define which groups in the assertion attribute are to have the Admin and
   * Editor roles in the workspace.
   */
  public readonly samlConfiguration?: SamlConfiguration;

  /**
   * The name of the AWS CloudFormation stack set that is used to generate IAM roles to be used for
   * this workspace.
   */
  public readonly stackSetName?: string;

  /**
   * The configuration settings for an Amazon VPC that contains data sources for your Grafana
   * workspace to connect to.
   */
  public readonly vpcConfiguration?: VpcConfiguration;

  /**
   * The underlying CloudFormation resource.
   */
  private readonly workspace: CfnWorkspace;

  /**
   * The date that the workspace was created.
   *
   * @attribute
   */
  public readonly creationTimestamp?: string;

  /**
   * The URL that users can use to access the Grafana console in the workspace.
   *
   * @attribute
   */
  public readonly endpoint?: string;

  /**
   * Specifies the version of Grafana supported by this workspace.
   *
   * @attribute
   */
  public readonly grafanaVersion?: string;

  /**
   * The unique ID of this workspace.
   *
   * @attribute
   */
  public readonly workspaceId: string;

  /**
   * The most recent date that the workspace was modified.
   *
   * @attribute
   */
  public readonly modificationTimestamp?: string;

  /**
   * Specifies whether the workspace's SAML configuration is complete.
   *
   * This is a deploy-time CloudFormation attribute resolved as an unresolved token at synth time,
   * so it is typed as `string`. See the `SamlConfigurationStatuses` enum for the possible values.
   *
   * @attribute
   */
  public readonly samlConfigurationStatus?: string;

  /**
   * The ID of the IAM Identity Center-managed application that is created by Amazon Managed
   * Grafana.
   *
   * @attribute
   */
  public readonly ssoClientId?: string;

  /**
   * The current status of the workspace.
   *
   * This is a deploy-time CloudFormation attribute resolved as an unresolved token at synth time,
   * so it is typed as `string`. See the `Status` enum for the possible values.
   *
   * @attribute
   */
  public readonly status?: string;

  /**
   * The arn of this workspace.
   */
  public readonly workspaceArn: string;

  constructor(scope: Construct, id: string, props: WorkspaceProps) {
    super(scope, id);

    Object.defineProperty(this, IS_WORKSPACE, { value: true });

    this.accountAccessType = props.accountAccessType;
    this.authenticationProviders = props.authenticationProviders;
    this.clientToken = props.clientToken;
    this.dataSources = props.dataSources;
    this.description = props.description;
    this.networkAccessControl = props.networkAccessControl;
    this.notificationDestinations = props.notificationDestinations;
    this.organizationalUnits = props.organizationalUnits;
    this.organizationRoleName = props.organizationRoleName;
    this.permissionType = props.permissionType;
    this.pluginAdminEnabled = props.pluginAdminEnabled;
    this.name = props.name;
    this.role = props.role;
    this.samlConfiguration = props.samlConfiguration;
    this.stackSetName = props.stackSetName;
    this.vpcConfiguration = props.vpcConfiguration;

    const samlConfiguration = props.samlConfiguration;

    const cfnWorkspaceProps: CfnWorkspaceProps = {
      accountAccessType: props.accountAccessType,
      authenticationProviders: props.authenticationProviders,
      clientToken: props.clientToken,
      dataSources: props.dataSources,
      description: props.description,
      grafanaVersion: props.grafanaVersion,
      name: props.name,
      networkAccessControl: props.networkAccessControl
        ? {
          // Map the strongly-typed prefix lists / VPC endpoints to their ids. `?.map` preserves
          // the three meaningful states: absent (undefined), explicitly empty (`[]` = "allow
          // none"), and populated. An empty array is intentionally NOT collapsed to undefined so
          // the "deny all traffic" semantics survive to the synthesized template.
          prefixListIds: props.networkAccessControl.prefixLists?.map(
            (prefixList) => prefixList.prefixListId,
          ),
          vpceIds: props.networkAccessControl.vpcEndpoints?.map(
            (vpcEndpoint) => vpcEndpoint.vpcEndpointId,
          ),
        }
        : undefined,
      notificationDestinations: props.notificationDestinations,
      organizationalUnits: props.organizationalUnits,
      organizationRoleName: props.organizationRoleName,
      permissionType: props.permissionType,
      pluginAdminEnabled: props.pluginAdminEnabled,
      roleArn: props.role?.roleArn,
      samlConfiguration: samlConfiguration
        ? {
          allowedOrganizations: samlConfiguration.allowedOrganizations,
          assertionAttributes: samlConfiguration.assertionAttributes,
          idpMetadata: samlConfiguration.idpMetadata,
          loginValidityDuration: samlConfiguration.loginValidityDuration,
          roleValues: samlConfiguration.roleValues,
        }
        : undefined,
      stackSetName: props.stackSetName,
      // The L1 CfnWorkspace (aws-cdk-lib 2.266+) is `ITaggableV2` and accepts tags natively as a
      // list of { key, value }. Seed it from the optional `props.tags` map; tags applied later via
      // `Tags.of(workspace).add(...)` aspects merge into the same list at synth time.
      tags: props.tags
        ? Object.entries(props.tags).map(([key, value]) => ({ key, value }))
        : undefined,
      vpcConfiguration: props.vpcConfiguration
        ? {
          securityGroupIds: props.vpcConfiguration.securityGroups.map(
            (sg) => sg.securityGroupId,
          ),
          subnetIds: props.vpcConfiguration.subnets.map(
            (subnet) => subnet.subnetId,
          ),
        }
        : undefined,
    };

    this.workspace = new CfnWorkspace(this, 'Resource', cfnWorkspaceProps);
    this.node.defaultChild = this.workspace;

    this.creationTimestamp = this.workspace.attrCreationTimestamp;
    this.endpoint = this.workspace.attrEndpoint;
    this.grafanaVersion = this.workspace.attrGrafanaVersion;
    this.workspaceId = this.workspace.attrId;
    this.modificationTimestamp = this.workspace.attrModificationTimestamp;
    this.samlConfigurationStatus = this.workspace.attrSamlConfigurationStatus;
    this.ssoClientId = this.workspace.attrSsoClientId;
    this.status = this.workspace.attrStatus;
    this.workspaceArn = this.getWorkspaceArn(this.workspaceId);
  }
}
